spec_version: 1.2

datasources:
  tzkt:
    kind: tzkt
    url: ${TZKT_URL:-https://api.ghostnet.tzkt.io}
    http:
      connection_timeout: 60
  metadata:
    kind: metadata
    url: https://metadata.dipdup.net
    network: mainnet
  ipfs:
    kind: ipfs
    url: https://ipfs.io/ipfs

hooks:
  process_missing_metadata_for_token:
    callback: process_missing_metadata_for_token
    atomic: False
  process_missing_metadata_for_collection:
    callback: process_missing_metadata_for_collection
    atomic: False

jobs:
  process_missing_metadata_for_token:
    hook: process_missing_metadata_for_token
    crontab: "* * * * *"
  process_missing_metadata_for_collection:
    hook: process_missing_metadata_for_collection
    crontab: "* * * * *"

advanced:
  rollback_depth: 2
  early_realtime: True
  metadata_interface: True
  reindex:
    manual: wipe
    migration: exception
    rollback: ignore
    config_modified: ignore
    schema_modified: ignore

custom:
  enabled: ${KAFKA_ENABLED:-false}
  kafka_address: ${KAFKA_ADDRESS:-kafka:9092}
  client_id: dipdup-rarible-${APPLICATION_ENVIRONMENT:-mainnet}-producer
  kafka_security_protocol: ${KAFKA_SECURITY_PROTOCOL:-SASL_PLAINTEXT}
  sasl:
    mechanism: ${KAFKA_SASL_MECHANISM:-PLAIN}
    username: ${KAFKA_USERNAME:-rarible}
    password: ${KAFKA_PASSWORD:-changeme}