spec_version: 1.2

datasources:
  tzkt:
    kind: tzkt
    url: ${TZKT_URL:-https://api.ghostnet.tzkt.io}
    http:
      connection_timeout: 60

contracts:
  rarible_exchange:
    address: KT1NcKyhPnomH9PKGeDfvMiGH2PDgKCd5YuM
    typename: rarible_exchange
  rarible_bids:
    address: KT1MwKGYWWbXtfYdnQfwspwz5ZGfqGwiJuQF
    typename: rarible_bids
  rarible_aggregator_tracker:
    address: KT1DajvCNVScudRm3kCHPfUjsRCtmPnm375s
    typename: rarible_aggregator_tracker
  objkt_v1:
    address: KT1Ax5fm2UNxjXGmrMDytREfqvYoCXoBB4Jo
    typename: objkt_marketplace
  objkt_v2:
    address: KT1GiZuR6TdkgxZGQGZSdbC3Jox9JTSbqTB6
    typename: objkt_marketplace_v2
  hen:
    address: KT1XYgjgFQutFfgEiD7RuppSKZsawZbkpKxL
    typename: hen_marketplace
  teia_v1:
    address: KT1Anx515N2PK8A2ZX5uGNn7Gckh4WytLJmK
    typename: teia_v1
  versum_v1:
    address: KT1B1Wz7jPH23EqKUpDwFDkw3A1yLxGZ4uJy
    typename: versum_v1
  fxhash_v1:
    address: KT1BEc3m6yxN856Y4zfArpDqQ1uZZ1HkDTRh
    typename: fxhash_v1
  fxhash_v2:
    address: KT1GCLoBSwUaNjaGXq5RtiP8CXTL3cEeMNDs
    typename: fxhash_v2

indexes:
  rarible_exchange_actions:
    kind: operation
    datasource: tzkt
    contracts:
      - rarible_exchange
    types:
      - transaction
    handlers:
      - callback: rarible_order_list
        pattern:
          - destination: rarible_exchange
            type: transaction
            entrypoint: sell
      - callback: rarible_order_cancel_list
        pattern:
          - destination: rarible_exchange
            type: transaction
            entrypoint: cancel_sale
      - callback: rarible_order_match
        pattern:
          - destination: rarible_exchange
            type: transaction
            entrypoint: buy

  rarible_bids_actions:
    kind: operation
    datasource: tzkt
    contracts:
      - rarible_bids
    types:
      - transaction
    handlers:
      - callback: rarible_put_bid
        pattern:
          - destination: rarible_bids
            type: transaction
            entrypoint: put_bid
#      - callback: rarible_put_floor_bid
#        pattern:
#          - destination: rarible_bids
#            type: transaction
#            entrypoint: put_floor_bid
      - callback: rarible_accept_bid
        pattern:
          - destination: rarible_bids
            type: transaction
            entrypoint: accept_bid
#      - callback: rarible_accept_floor_bid
#        pattern:
#          - destination: rarible_bids
#            type: transaction
#            entrypoint: accept_floor_bid
      - callback: rarible_cancel_bid
        pattern:
          - destination: rarible_bids
            type: transaction
            entrypoint: cancel_bid
#      - callback: rarible_cancel_floor_bid
#        pattern:
#          - destination: rarible_bids
#            type: transaction
#            entrypoint: cancel_floor_bid

  hen_actions:
    kind: operation
    datasource: tzkt
    contracts:
      - hen
    types:
      - transaction
    handlers:
      - callback: hen_order_list
        pattern:
          - destination: hen
            type: transaction
            entrypoint: swap
      - callback: hen_order_cancel_list
        pattern:
          - destination: hen
            type: transaction
            entrypoint: cancel_swap
      - callback: hen_order_match
        pattern:
          - destination: hen
            type: transaction
            entrypoint: collect

  objkt_v1_actions:
    kind: operation
    datasource: tzkt
    contracts:
      - objkt_v1
    types:
      - transaction
    handlers:
      - callback: objkt_v1_order_list
        pattern:
          - destination: objkt_v1
            type: transaction
            entrypoint: ask
      - callback: objkt_v1_order_cancel_list
        pattern:
          - destination: objkt_v1
            type: transaction
            entrypoint: retract_ask
      - callback: objkt_v1_order_match
        pattern:
          - destination: objkt_v1
            type: transaction
            entrypoint: fulfill_ask
      - callback: objkt_v1_put_bid
        pattern:
         - destination: objkt_v1
           entrypoint: bid
      - callback: objkt_v1_cancel_bid
        pattern:
         - destination: objkt_v1
           entrypoint: retract_bid
      - callback: objkt_v1_accept_bid
        pattern:
         - destination: objkt_v1
           entrypoint: fulfill_bid

  objkt_v2_actions:
    kind: operation
    datasource: tzkt
    contracts:
      - objkt_v2
    types:
      - transaction
    handlers:
      - callback: objkt_v2_order_list
        pattern:
          - destination: objkt_v2
            entrypoint: ask
            type: transaction
      - callback: objkt_v2_order_cancel_list
        pattern:
          - destination: objkt_v2
            entrypoint: retract_ask
            type: transaction
      - callback: objkt_v2_order_match
        pattern:
          - destination: objkt_v2
            type: transaction
            entrypoint: fulfill_ask
      - callback: objkt_v2_put_bid
        pattern:
         - destination: objkt_v2
           entrypoint: offer
      - callback: objkt_v2_cancel_bid
        pattern:
         - destination: objkt_v2
           entrypoint: retract_offer
      - callback: objkt_v2_accept_bid
        pattern:
         - destination: objkt_v2
           entrypoint: fulfill_offer

  teia_v1_actions:
    kind: operation
    datasource: tzkt
    contracts:
      - teia_v1
    types:
      - transaction
    handlers:
      - callback: teia_v1_list_order
        pattern:
          - destination: teia_v1
            type: transaction
            entrypoint: swap
      - callback: teia_v1_cancel_order
        pattern:
          - destination: teia_v1
            type: transaction
            entrypoint: cancel_swap
      - callback: teia_v1_match_order
        pattern:
          - destination: teia_v1
            type: transaction
            entrypoint: collect

  versum:
    kind: operation
    datasource: tzkt
    contracts:
      - versum_v1
    types:
      - transaction
    handlers:
      - callback: versum_v1_order_list
        pattern:
          - type: transaction
            destination: versum_v1
            entrypoint: create_swap
      - callback: versum_v1_order_cancel
        pattern:
          - type: transaction
            destination: versum_v1
            entrypoint: cancel_swap
      - callback: versum_v1_order_match
        pattern:
          - type: transaction
            destination: versum_v1
            entrypoint: collect_swap
      - callback: versum_v1_put_bid
        pattern:
          - type: transaction
            destination: versum_v1
            entrypoint: make_offer
      - callback: versum_v1_cancel_bid
        pattern:
          - type: transaction
            destination: versum_v1
            entrypoint: cancel_offer
      - callback: versum_v1_accept_bid
        pattern:
          - type: transaction
            destination: versum_v1
            entrypoint: accept_offer

  fxhash_v1_actions:
    kind: operation
    datasource: tzkt
    contracts:
      - fxhash_v1
    types:
      - transaction
    handlers:
      - callback: fxhash_v1_order_list
        pattern:
          - destination: fxhash_v1
            type: transaction
            entrypoint: offer
      - callback: fxhash_v1_order_cancel
        pattern:
          - destination: fxhash_v1
            type: transaction
            entrypoint: cancel_offer
      - callback: fxhash_v1_order_match
        pattern:
          - destination: fxhash_v1
            type: transaction
            entrypoint: collect

  fxhash_v2_actions:
     kind: operation
     datasource: tzkt
     contracts:
       - fxhash_v2
     types:
       - transaction
     handlers:
       - callback: fxhash_v2_listing_order_list
         pattern:
           - destination: fxhash_v2
             type: transaction
             entrypoint: listing
       - callback: fxhash_v2_listing_order_cancel
         pattern:
           - destination: fxhash_v2
             type: transaction
             entrypoint: listing_cancel
       - callback: fxhash_v2_listing_order_match
         pattern:
           - destination: fxhash_v2
             type: transaction
             entrypoint: listing_accept
       - callback: fxhash_v2_put_bid
         pattern:
           - destination: fxhash_v2
             entrypoint: offer
       - callback: fxhash_v2_cancel_bid
         pattern:
           - destination: fxhash_v2
             entrypoint: offer_cancel
       - callback: fxhash_v2_accept_bid
         pattern:
           - destination: fxhash_v2
             entrypoint: offer_accept

  rarible_aggregator_tracker_events:
    kind: event
    datasource: tzkt
    handlers:
      - callback: on_rarible_aggregator_event
        contract: rarible_aggregator_tracker
        tag: aggregator_event

  token_transfers:
    kind: token_transfer
    datasource: tzkt
    handlers:
      - callback: on_transfer

  originations:
    kind: head
    datasource: tzkt
    handlers:
      - callback: on_head
hooks:
  process_collection_events:
    callback: process_collection_events
    atomic: False
    args:
      level: int
  process_transaction_hash:
    callback: process_transaction_hash
    atomic: False
  process_tasks:
    callback: process_tasks
    atomic: False
  reset_index:
    callback: reset_index
    atomic: False
    args:
      id: int
#  fill_db_updated_at:
#    callback: fill_db_updated_at
#    atomic: False
#    args:
#      batch: 10000
#  fix_db_updated_at:
#    callback: fix_db_updated_at
#    atomic: False
#    args:
#      batch: 10000

jobs:
  process_transaction_hash:
    hook: process_transaction_hash
    interval: 300 # seconds
    args:
      iterations: 10
      batch: 100
  process_tasks:
    hook: process_tasks
    interval: 60 # seconds
#  fill_db_updated_at:
#    hook: fill_db_updated_at
#    interval: 30 # seconds

advanced:
  rollback_depth: 2
  early_realtime: True
  reindex:
    manual: wipe
    migration: exception
    rollback: ignore
    config_modified: ignore
    schema_modified: ignore

custom:
  enabled: ${KAFKA_ENABLED:-false}
  kafka_address: ${KAFKA_ADDRESS:-kafka:9092}
  client_id: dipdup-rarible-${APPLICATION_ENVIRONMENT:-mainnet}-producer
  kafka_security_protocol: ${KAFKA_SECURITY_PROTOCOL:-SASL_PLAINTEXT}
  sasl:
    mechanism: ${KAFKA_SASL_MECHANISM:-PLAIN}
    username: ${KAFKA_USERNAME:-rarible}
    password: ${KAFKA_PASSWORD:-changeme}
  token_indexing:
    enabled: true
  run_fix_jobs: False
  first_collection_level: 0
  fxhash_nft_v1: KT1VEXkw6rw6pJDP9APGsMneFafArijmM96j
  fxhash_nft_v2: KT1WSwXCWPPAxAy4ibPmFyCm4NhmSJT9UuxQ
