datasources:
  tzkt:
    kind: tzkt
    url: ${TZKT_URL:-https://api.tzkt.io}
    http:
      batch_size: 5000

contracts:
  rarible_exchange_legacy:
    address: KT198mqFKkiWerXLmMCw69YB1i6yzYtmGVrC
    typename: rarible_exchange_legacy
  rarible_exchange_legacy_data:
    address: KT1D2fZiUNo6RPj3zKofH8DqDDgoV7KoyEbb
    typename: rarible_exchange_legacy_data
  rarible_exchange:
    address: KT1N4Rrm6BU6229drs6scrH3vard1pPngMyA
    typename: rarible_exchange

indexes:
  token_transfers:
    kind: token_transfer
    datasource: tzkt
    first_level: 2614021
    handlers:
      - callback: on_transfer


  rarible_exchange_actions:
    kind: operation
    datasource: tzkt
    contracts:
        - rarible_exchange
    handlers:
        - callback: rarible_order_list
          pattern:
            - destination: rarible_exchange
              entrypoint: sell
        - callback: rarible_order_cancel_list
          pattern:
            - destination: rarible_exchange
              entrypoint: cancel_sale
        - callback: rarible_order_match
          pattern:
            - destination: rarible_exchange
              entrypoint: buy

  rarible_exchange_legacy_actions:
    kind: operation
    datasource: tzkt
    contracts:
      - rarible_exchange_legacy
    handlers:
      - callback: rarible_match_orders_legacy
        pattern:
          - destination: rarible_exchange_legacy
            entrypoint: match_orders

  rarible_exchange_legacy_data_actions:
    kind: operation
    datasource: tzkt
    contracts:
      - rarible_exchange_legacy_data
    handlers:
      - callback: rarible_cancel_order_legacy
        pattern:
          - destination: rarible_exchange_legacy_data
            entrypoint: remove

hooks:
  process_collection_events:
    callback: process_collection_events
    atomic: False
    args:
      force_reindex: bool
      head: int
  import_legacy_orders:
    callback: import_legacy_orders
    atomic: False

advanced:
  rollback_depth: 2
  early_realtime: True
  skip_version_check: False
  reindex:
    manual: wipe
    migration: exception
    rollback: ignore
    config_modified: ignore
    schema_modified: ignore

prometheus:
  host: 0.0.0.0
  port: 9191
  update_interval: 5