spec_version: 1.2
package: rarible_marketplace_indexer

database:
  kind: postgres
  host: ${POSTGRES_HOST:-db}
  port: ${POSTGRES_PORT:-5432}
  user: ${POSTGRES_USER:-dipdup}
  password: ${POSTGRES_PASS:-changeme}
  database: ${POSTGRES_DB:-dipdup}

hasura:
  url: ${HASURA_URL:-http://hasura:8080}
  admin_secret: ${HASURA_GRAPHQL_ADMIN_SECRET:-changeme}
  select_limit: ${HASURA_SELECT_LIMIT:-1000}
  allow_aggregations: true
  rest: true

datasources:
  tzkt:
    kind: tzkt
    url: ${TZKT_URL:-https://api.tzkt.io}
    http:
      retry_count: 5
      retry_sleep: 5
      connection_limit: 1000
      connection_timeout: 60
      batch_size: 1000
  metadata:
    kind: metadata
    url: https://metadata.dipdup.net
    network: mainnet
    http:
      retry_count: 5
      retry_sleep: 5
      connection_limit: 1000
      connection_timeout: 60
      batch_size: 1000
  ipfs:
    kind: ipfs
    url: https://cloudflare-ipfs.com/ipfs
    http:
      retry_count: 5
      retry_sleep: 5
      connection_limit: 1000
      connection_timeout: 60
      batch_size: 1000