spec_version: 1.2
package: rarible_marketplace_indexer

datasources:
  tzkt:
    kind: tzkt
    url: ${TZKT_URL:-https://api.tzkt.io}
    http:
      retry_count: 5
      retry_sleep: 5
      connection_limit: 1000
      connection_timeout: 60
      batch_size: 1000
  metadata:
    kind: metadata
    url: https://metadata.dipdup.net
    network: mainnet
    http:
      retry_count: 5
      retry_sleep: 5
      connection_limit: 1000
      connection_timeout: 60
      batch_size: 1000
  ipfs:
    kind: ipfs
    url: http://ipfs-gw1.ext.rarible.com:8080/ipfs
    http:
      retry_count: 1
      retry_sleep: 0
      connection_limit: 100
      connection_timeout: 60
      batch_size: 10000
  objkt:
    kind: http
    url: https://data.objkt.com

hasura:
  url: ${HASURA_URL:-http://hasura:8080}
  admin_secret: ${HASURA_GRAPHQL_ADMIN_SECRET:-changeme}
  select_limit: ${HASURA_SELECT_LIMIT:-1000}
  allow_aggregations: False
  rest: true

hooks:
  process_token_royalties:
    callback: process_token_royalties
    atomic: False

jobs:
  process_token_royalties:
    hook: process_token_royalties
    crontab: "* * * * *"

advanced:
  rollback_depth: 0
  early_realtime: False
  metadata_interface: True
  merge_subscriptions: True
  reindex:
    manual: wipe
    migration: exception
    rollback: ignore
    config_modified: ignore
    schema_modified: ignore

custom:
  enabled: ${KAFKA_ENABLED:-false}
  kafka_address: ${KAFKA_ADDRESS:-kafka:9092}
  client_id: dipdup-rarible-${APPLICATION_ENVIRONMENT:-mainnet}-producer
  kafka_security_protocol: ${KAFKA_SECURITY_PROTOCOL:-SASL_PLAINTEXT}
  sasl:
    mechanism: ${KAFKA_SASL_MECHANISM:-PLAIN}
    username: ${KAFKA_USERNAME:-rarible}
    password: ${KAFKA_PASSWORD:-changeme}
  run_fix_jobs: False
  royalties:
    hen: "KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton"
    hen_royalties: "KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9"
    kalamint: "KT1EpGgjQs73QfFJs9z7m1Mxm5MTnpC2tqse"
    fxhash_v1: "KT1KEa8z6vWXDJrVqtMrAeDVzsvxat3kHaCE"
    fxhash_v1_manager: "KT1XCoGnfupWk7Sp8536EfrxcP73LmT68Nyr"
    fxhash_v2: "KT1U6EHmNxJTkvaWJ4ThczG4FSDaHC21ssvi"
    fxhash_v2_2: "KT1EfsNuqwLAWDd3o4pvfUx1CAh5GMdTrRvr"
    versum: "KT1LjmAdYQCLBjwv4S2oFkEzyHVkomAf5MrW"
    royalties_manager: "KT1HNNrmCk1fpqveRDz8Fvww2GM4gPzmA7fo"
    bidou_8x8: "KT1MxDwChiDwd6WBVs24g1NjERUoK622ZEFp"
    bidou_24x24: "KT1TR1ErEQPTdtaJ7hbvKTJSa1tsGnHGZTpf"
    bidou_24x24_color: "KT1VikAWA8wQHLZgHoAGL7Z9kCjgbCEnvWA3"
    dogami: "KT1NVvPsNDChrLRH5K2cy6Sc9r1uuUwdiZQd"
    dogami_gap: "KT1CAbPGHUWvkSA9bxMPkqSgabgsjtmRYEda"
