datasources:
  tzkt:
    kind: tzkt
    url: ${TZKT_URL:-https://api.tzkt.io}
    http:
      batch_size: 5000

contracts:
  versum_v1:
    address: KT1GyRAJNdizF1nojQz62uGYkx8WFRUJm9X5
    typename: versum_v1
  teia_v1:
    address: KT1PHubm9HtyQEJ4BBpMTVomq6mhbfNZ9z5w
    typename: teia_v1
  hen:
    address: KT1HbQepzV1nVGg8QVznG7z4RcHseD5kwqBn
    typename: hen_marketplace
  objkt_v1:
    address: KT1FvqJwEDWb1Gwc55Jd1jjTHRVWbYKUUpyq
    typename: objkt_marketplace
  objkt_v2:
    address: KT1WvzYHCNBvDSdwafTHv7nJ1dWmZ8GCYuuC
    typename: objkt_marketplace_v2

indexes:
  hen_actions:
    kind: operation
    datasource: tzkt
    contracts:
      - hen
    types:
      - transaction
    handlers:
      - callback: hen_order_list
        pattern:
          - destination: hen
            type: transaction
            entrypoint: swap
      - callback: hen_order_cancel_list
        pattern:
          - destination: hen
            type: transaction
            entrypoint: cancel_swap
      - callback: hen_order_match
        pattern:
          - destination: hen
            type: transaction
            entrypoint: collect

  objkt_v1_actions:
    kind: operation
    datasource: tzkt
    contracts:
      - objkt_v1
    types:
      - transaction
    handlers:
      - callback: objkt_order_list
        pattern:
          - destination: objkt_v1
            type: transaction
            entrypoint: ask
      - callback: objkt_order_cancel_list
        pattern:
          - destination: objkt_v1
            type: transaction
            entrypoint: retract_ask
      - callback: objkt_order_match
        pattern:
          - destination: objkt_v1
            type: transaction
            entrypoint: fulfill_ask

  objkt_v2_actions:
    kind: operation
    datasource: tzkt
    contracts:
      - objkt_v2
    types:
      - transaction
    handlers:
      - callback: objkt_v2_order_list
        pattern:
          - destination: objkt_v2
            type: transaction
            entrypoint: ask
      - callback: objkt_v2_order_cancel_list
        pattern:
          - destination: objkt_v2
            type: transaction
            entrypoint: retract_ask
      - callback: objkt_v2_order_match
        pattern:
          - destination: objkt_v2
            type: transaction
            entrypoint: fulfill_ask

  teia_v1_actions:
     kind: operation
     datasource: tzkt
     contracts:
       - teia_v1
     types:
       - transaction
     handlers:
       - callback: teia_v1_list_order
         pattern:
           - destination: teia_v1
             type: transaction
             entrypoint: swap
       - callback: teia_v1_cancel_order
         pattern:
           - destination: teia_v1
             type: transaction
             entrypoint: cancel_swap
       - callback: teia_v1_match_order
         pattern:
           - destination: teia_v1
             type: transaction
             entrypoint: collect

  versum:
    kind: operation
    datasource: tzkt
    contracts:
      - versum_v1
    types:
      - transaction
    handlers:
      - callback: versum_v1_order_list
        pattern:
          - type: transaction
            destination: versum_v1
            entrypoint: create_swap
      - callback: versum_v1_order_cancel
        pattern:
          - type: transaction
            destination: versum_v1
            entrypoint: cancel_swap
      - callback: versum_v1_order_match
        pattern:
          - type: transaction
            destination: versum_v1
            entrypoint: collect_swap

advanced:
  rollback_depth: 2
  early_realtime: True
  skip_version_check: False
  reindex:
    manual: wipe
    migration: exception
    rollback: ignore
    config_modified: ignore
    schema_modified: ignore

prometheus:
  host: 0.0.0.0
  port: 9191
  update_interval: 5