spec_version: 1.2

hooks:
  consume_ownerships:
    callback: consume_ownerships
    atomic: False
  process_transaction_hash:
    callback: process_transaction_hash
    atomic: False

jobs:
  process_transaction_hash:
    hook: process_transaction_hash
    interval: 60 # seconds
    args:
      iterations: 10
      batch: 100

indexes:
  token_transfers:
    kind: token_transfer
    datasource: tzkt
    first_level: 1212040
    handlers:
      - callback: on_transfer

advanced:
  rollback_depth: 0
  early_realtime: False
  metadata_interface: True
  merge_subscriptions: True
  reindex:
    manual: wipe
    migration: exception
    rollback: ignore
    config_modified: ignore
    schema_modified: ignore

custom:
  enabled: ${KAFKA_ENABLED:-false}
  kafka_address: ${KAFKA_ADDRESS:-kafka:9092}
  client_id: dipdup-rarible-${APPLICATION_ENVIRONMENT:-mainnet}-producer
  kafka_security_protocol: ${KAFKA_SECURITY_PROTOCOL:-SASL_PLAINTEXT}
  sasl:
    mechanism: ${KAFKA_SASL_MECHANISM:-PLAIN}
    username: ${KAFKA_USERNAME:-rarible}
    password: ${KAFKA_PASSWORD:-changeme}
  run_fix_jobs: False
  royalties:
    hen: "KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton"
    hen_royalties: "KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9"
    kalamint: "KT1EpGgjQs73QfFJs9z7m1Mxm5MTnpC2tqse"
    fxhash_v1: "KT1KEa8z6vWXDJrVqtMrAeDVzsvxat3kHaCE"
    fxhash_v1_manager: "KT1XCoGnfupWk7Sp8536EfrxcP73LmT68Nyr"
    fxhash_v2: "KT1U6EHmNxJTkvaWJ4ThczG4FSDaHC21ssvi"
    versum: "KT1LjmAdYQCLBjwv4S2oFkEzyHVkomAf5MrW"
    royalties_manager: "KT1HNNrmCk1fpqveRDz8Fvww2GM4gPzmA7fo"
    bidou_8x8: "KT1MxDwChiDwd6WBVs24g1NjERUoK622ZEFp"
    bidou_24x24: "KT1TR1ErEQPTdtaJ7hbvKTJSa1tsGnHGZTpf"
    bidou_24x24_color: "KT1VikAWA8wQHLZgHoAGL7Z9kCjgbCEnvWA3"
    dogami: "KT1NVvPsNDChrLRH5K2cy6Sc9r1uuUwdiZQd"
    dogami_gap: "KT1CAbPGHUWvkSA9bxMPkqSgabgsjtmRYEda"
