[tool.isort]
line_length = 120
force_single_line = true
group_by_package = true
ensure_newline_before_comments = true

[tool.black]
line-length = 120
target-version = ["py310"]
skip-string-normalization = true

[tool.flakeheaven]
format = "colored"
max_line_length = 120
show_source = true
extended_default_ignore = []

[tool.flakeheaven.plugins]
pyflakes = ["+*"]
pycodestyle = ["+*", "-E203"]