delete from dipdup_index where name = 'rarible_exchange_actions';
delete from dipdup_index where name = 'rarible_exchange_legacy_actions';
delete from dipdup_index where name = 'rarible_exchange_legacy_data_actions';
delete from marketplace_order where platform = 'RARIBLE_V1';
delete from marketplace_order where platform = 'RARIBLE_V2';
delete from marketplace_activity where platform = 'RARIBLE_V1';
delete from marketplace_activity where platform = 'RARIBLE_V2';
delete from indexing_status where index = 'V1_CLEANING';
delete from indexing_status where index = 'V1_FILL_FIX';
delete from indexing_status where index = 'LEGACY_ORDERS';
delete from legacy_orders;