# generated by datamodel-codegen:
#   filename:  cancel.json

from __future__ import annotations

from typing import Any
from typing import Optional
from typing import Union

from pydantic import BaseModel
from pydantic import Extra


class FA2AssetClass(BaseModel):
    class Config:
        extra = Extra.forbid

    FA_2: Optional[str]


class FA12AssetClass(BaseModel):
    class Config:
        extra = Extra.forbid

    FA_1_2: Optional[Any]


class XTZAssetClass(BaseModel):
    class Config:
        extra = Extra.forbid

    XTZ: Optional[Any]


class AssetType(BaseModel):
    class Config:
        extra = Extra.forbid

    asset_class: Union[FA2AssetClass, FA12AssetClass, XTZAssetClass]
    asset_data: str


class Asset(BaseModel):
    class Config:
        extra = Extra.forbid

    asset_type: AssetType
    asset_value: str


class CancelParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    maker: Optional[str]
    make_asset: Asset
    taker: Optional[str]
    take_asset: Asset
    salt: str
    start: Optional[str]
    end: Optional[str]
    data_type: str
    data: str
