# generated by datamodel-codegen:
#   filename:  accept_floor_bid.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel
from pydantic import Extra

from rarible_marketplace_indexer.types.rarible_exchange.parameter.sell import Part


class AcceptFloorBidParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    afb_asset_contract: str
    afb_asset_token_id: str
    afb_bidder: str
    afb_bid_type: str
    afb_bid_asset: str
    afb_origin_fees: List[Part]
    afb_payouts: List[Part]
