# generated by datamodel-codegen:
#   filename:  accept_bid.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel
from pydantic import Extra

from rarible_marketplace_indexer.types.rarible_exchange.parameter.sell import Part


class AcceptBidParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    ab_asset_contract: str
    ab_asset_token_id: str
    ab_bidder: str
    ab_bid_type: str
    ab_bid_asset: str
    ab_origin_fees: List[Part]
    ab_payouts: List[Part]
