# generated by datamodel-codegen:
#   filename:  put_floor_bid.json

from __future__ import annotations

from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Extra

from rarible_marketplace_indexer.types.rarible_exchange.parameter.sell import Part

class PfbBid(BaseModel):
    class Config:
        extra = Extra.forbid

    bid_origin_fees: List[Part]
    bid_payouts: List[Part]
    bid_amount: str
    bid_asset_qty: str
    bid_expiry_date: Optional[str]
    bid_data_type: Optional[str]
    bid_data: Optional[str]


class PutFloorBidParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    pfb_asset_contract: str
    pfb_bid_type: str
    pfb_bid_asset: str
    pfb_bid: PfbBid
