# generated by datamodel-codegen:
#   filename:  create_swap.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from pydantic import Extra


class CurrencyItem(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str
    nat: str


class Token(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str
    nat: str


class CreateSwapParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    burn_on_end: bool
    collect_max_per_tx: str
    currency: Optional[CurrencyItem]
    ending_price_in_nat: str
    ending_time: Optional[str]
    require_verified: bool
    starting_price_in_nat: str
    token: Token
    token_amount: str
