# generated by datamodel-codegen:
#   filename:  make_offer.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from pydantic import Extra


class CurrencyItem(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str
    nat: str


class Token(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str
    nat: str


class MakeOfferParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    currency: Optional[CurrencyItem]
    price_in_nat: str
    require_verified: bool
    token: Token
    token_amount: str
