delete from "royalties";
delete from "collection";
delete from "metadata_collection";
delete from "metadata_token";
delete from "ownership";
delete from "token";
delete from "token_transfer";
delete from dipdup_index where name = 'token_transfers';
delete from dipdup_index where name = 'originations';
delete from indexing_status where index = 'COLLECTION';
delete from indexing_status where index = 'COLLECTION_METADATA';
delete from indexing_status where index = 'NFT_METADATA';
alter table indexing_status alter column index type character varying(20);