# generated by datamodel-codegen:
#   filename:  aggregator_event.json

from __future__ import annotations

from pydantic import BaseModel


class AggregatorEventPayload(BaseModel):
    __root__: str
