# generated by datamodel-codegen:
#   filename:  fulfill_offer.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from pydantic import Extra


class FulfillOfferParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    offer_id: str
    token_id: Optional[str]
