{
 "title": "Tezos Indexing dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Tezos Global stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transaction processing speed (tx/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(dipdup_callback_duration_seconds_count{}[$__interval]))",
     "legendFormat": "{{callback}}"
    }
   ]
  },
  {
   "title": "Transactions pending processing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "dipdup_index_levels_to_sync_total_count",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Tezos token activities",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(dipdup_rarible_token_activity_count{index_type=\"ActivityTypeEnum.TOKEN_TRANSFER\"}[$__interval]))",
     "legendFormat": "Token transfers"
    },
    {
     "expr": "sum(rate(dipdup_rarible_token_activity_count{index_type=\"ActivityTypeEnum.TOKEN_MINT\"}[$__interval]))",
     "legendFormat": "Mints"
    },
    {
     "expr": "sum(rate(dipdup_rarible_token_activity_count{index_type=\"ActivityTypeEnum.TOKEN_BURN\"}[$__interval]))",
     "legendFormat": "Burns"
    }
   ]
  },
  {
   "title": "Tezos order activities",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(dipdup_rarible_order_activity_count{index_type=\"ActivityTypeEnum.ORDER_MATCH\"}[$__interval]))",
     "legendFormat": "Order match (all marketplaces)"
    },
    {
     "expr": "sum(rate(dipdup_rarible_order_activity_count{index_type=\"ActivityTypeEnum.ORDER_LIST\"}[$__interval]))",
     "legendFormat": "Order list (all marketplaces)"
    },
    {
     "expr": "sum(rate(dipdup_rarible_order_activity_count{index_type=\"ActivityTypeEnum.ORDER_CANCEL\"}[$__interval]))",
     "legendFormat": "Order cancel (all marketplaces)"
    }
   ]
  },
  {
   "title": "Totals",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "dipdup_rarible_order_activity_sum",
     "legendFormat": "{{index}} {{index_type}}"
    }
   ]
  },
  { "title": "Rarible", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Rarible activities",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "rate(dipdup_rarible_order_activity_count[$__interval])",
     "legendFormat": "{{index}} {{index_type}}"
    }
   ]
  },
  {
   "title": "Rarible totals",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dipdup_rarible_order_activity_sum",
     "legendFormat": "{{index}} {{index_type}}"
    }
   ]
  },
  { "title": "OBJKT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "OBJKT activities",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "rate(dipdup_rarible_order_activity_count[$__interval])",
     "legendFormat": "{{index}} {{index_type}}"
    }
   ]
  },
  {
   "title": "OBJKT totals",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dipdup_rarible_order_activity_count",
     "legendFormat": "{{index}} {{index_type}}"
    }
   ]
  },
  { "title": "HEN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "HEN activities",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "rate(dipdup_rarible_order_activity_count[$__interval])",
     "legendFormat": "{{index}} {{index_type}}"
    }
   ]
  },
  {
   "title": "HEN totals",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dipdup_rarible_order_activity_sum",
     "legendFormat": "{{index}} {{index_type}}"
    }
   ]
  }
 ]
}