# generated by datamodel-codegen:
#   filename:  listing.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class Gentk(BaseModel):
    class Config:
        extra = Extra.forbid

    id: str
    version: str


class ListingParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    gentk: Gentk
    price: str
