# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict
from typing import Optional

from pydantic import BaseModel
from pydantic import Extra


class RaribleExchangeLegacyStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    owner: str
    transfer_manager: str
    royalties: str
    fill: str
    owner_candidate: Optional[str]
    paused: bool
    metadata: Dict[str, str]
