# generated by datamodel-codegen:
#   filename:  default.json

from __future__ import annotations

from typing import List
from typing import Set
from typing import Union

from pydantic import BaseModel
from pydantic import Field


class ListItem(BaseModel):
    string_0: str
    bytes: str
    string_1: str


class DefaultParameter(BaseModel):
    list: Union[List[ListItem], Set[ListItem]] = Field([], alias="set")
    bool: bool
