{{- if .Values.global }}
{{- if .Values.tzkt.instances }}
---
apiVersion: v1
kind: Service
metadata:
  name: tzkt
  labels:
    app: tzkt
spec:
  {{- if .Values.tzkt.service.nodePort }}
  type: NodePort
  {{- else }}
  type: ClusterIP
  {{- end }}
  ports:
    - port: {{ .Values.tzkt.service.port }}
      name: http
      targetPort: {{ .Values.tzkt.service.port }}
      protocol: TCP
      {{- if .Values.tzkt.service.nodePort }}
      nodePort: {{ .Values.tzkt.service.nodePort }}
      {{- end }}
  selector:
    app: tzkt
{{ range $name := .Values.tzkt.instances }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      nodeSelector: 
        env: {{ include "app.env" $ | quote }}
      containers:
        - image: "{{ $.Values.tzkt.api.image.repository }}:{{ $.Values.tzkt.api.image.tag }}"
          name: api
          ports:
            - containerPort: {{ $.Values.tzkt.service.port }}
              name: http
              protocol: TCP
          env:
          - name: Kestrel__Endpoints__Http__Url
            value: http://0.0.0.0:{{ $.Values.tzkt.service.port }}
          {{- range $key, $value := $.Values.tzkt.environments }}
          - name: {{ $key }}
            {{- if $value }}
            value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          envFrom:
          - secretRef:
              name: apps-common
              optional: true
          - secretRef:
              name: tezos-marketplace-indexer-stack
              optional: true
          - secretRef:
              name: {{ $name }}
              optional: true
          resources:
            {{- toYaml $.Values.tzkt.api.resources | nindent 12 }}
        - image: "{{ $.Values.tzkt.indexer.image.repository }}:{{ $.Values.tzkt.indexer.image.tag }}"
          name: indexer
          env:
          - name: TokenMetadata__Enabled
            value: "true"
          {{- range $key, $value := $.Values.tzkt.environments }}
          - name: {{ $key }}
            {{- if $value }}
            value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          envFrom:
          - secretRef:
              name: apps-common
              optional: true
          - secretRef:
              name: tezos-marketplace-indexer-stack
              optional: true
          - secretRef:
              name: {{ $name }}
              optional: true
          command: ["/bin/bash", "-c"]
          args:
            - |
              # Set TezosNode__ChainId env var
              . /etc/tzkt/tzkt.env
              dotnet Tzkt.Sync.dll
          volumeMounts:
            - name: tzkt-config
              mountPath: /app/appsettings.json
              subPath: appsettings.json
          resources:
            {{- toYaml $.Values.tzkt.indexer.resources | nindent 12 }}
      volumes:
        - name: tzkt-config
          configMap:
            name: tzkt-config
{{- end }}
{{- end }}
{{- end }}